### PR TITLE
feat: add link :dog:

### LINKED ISSUE #2: why not create link page?
I'm looking at your book. thanks you very much.
but why not create a link page?
input URL is too slow.

### PR DESCRIPTION
**Pull request by yanhaijing**
fix #2

### CODE REVIEW

**Comment by yanhaijing** [comment]
now index page like this http://yanhaijing.com/play.csssecrets.io/
i think more convenient

**Comment by yanhaijing** [comment]
thanks you very much

**Comment by LeaVerou** [comment]
Thanks!

In the beginning because I didn't want non-readers to visit all the demos and get confused without context. In retrospect, I think I was wrong, convenience should win.

Please change the heading to "All demos"?

**Comment by yanhaijing** [comment]
i change it, like this?

**Comment by LeaVerou** [comment]
Not exactly, but I'll fix it myself later. Thanks, merged!

**Pull request merged**
